<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Surefire suite]" verbose="0">
  <test thread-count="5" name="Surefire test(failed)" verbose="0">
    <classes>
      <class name="kowsalyaLearning.tests.ErrorValidationsTest">
        <methods>
          <include name="launchApplication"/>
          <include name="LoginErrorValidations"/>
          <include name="tearDown"/>
          <include name="ProductErrorValidations"/>
        </methods>
      </class> <!-- kowsalyaLearning.tests.ErrorValidationsTest -->
      <class name="kowsalyaLearning.tests.SubmitOrderTest">
        <methods>
          <include name="launchApplication"/>
          <include name="submitOrder" invocation-numbers="0 1"/>
          <include name="orderHistoryTest"/>
          <include name="tearDown"/>
        </methods>
      </class> <!-- kowsalyaLearning.tests.SubmitOrderTest -->
      <class name="cucumber.TestNGRunnner">
        <methods>
          <include name="setUpClass"/>
          <include name="tearDownClass"/>
          <include name="runScenario" invocation-numbers="0 1 2"/>
        </methods>
      </class> <!-- cucumber.TestNGRunnner -->
    </classes>
  </test> <!-- Surefire test(failed) -->
</suite> <!-- Failed suite [Surefire suite] -->
